// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_BgM_a9lhVbiBFwt5Mq7JNMwyZDUR0qw',
    appId: '1:231653740465:web:ba08fd5416eea28cbbf790',
    messagingSenderId: '231653740465',
    projectId: 'migaskita-ff09c',
    authDomain: 'migaskita-ff09c.firebaseapp.com',
    storageBucket: 'migaskita-ff09c.firebasestorage.app',
    measurementId: 'G-F96PTL8NWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv3EesMMv8bRn1-pOImKo9zHO1E8FDXIU',
    appId: '1:231653740465:android:2b0628da010f7804bbf790',
    messagingSenderId: '231653740465',
    projectId: 'migaskita-ff09c',
    storageBucket: 'migaskita-ff09c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARU8j14scHX5--R3S4oEYPgBtMtPL783g',
    appId: '1:231653740465:ios:f5672bc977c60ef1bbf790',
    messagingSenderId: '231653740465',
    projectId: 'migaskita-ff09c',
    storageBucket: 'migaskita-ff09c.firebasestorage.app',
    iosBundleId: 'com.example.flutterMigaskita',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARU8j14scHX5--R3S4oEYPgBtMtPL783g',
    appId: '1:231653740465:ios:f5672bc977c60ef1bbf790',
    messagingSenderId: '231653740465',
    projectId: 'migaskita-ff09c',
    storageBucket: 'migaskita-ff09c.firebasestorage.app',
    iosBundleId: 'com.example.flutterMigaskita',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_BgM_a9lhVbiBFwt5Mq7JNMwyZDUR0qw',
    appId: '1:231653740465:web:0322f5dd22dfb657bbf790',
    messagingSenderId: '231653740465',
    projectId: 'migaskita-ff09c',
    authDomain: 'migaskita-ff09c.firebaseapp.com',
    storageBucket: 'migaskita-ff09c.firebasestorage.app',
    measurementId: 'G-KN2XSV0F6P',
  );
}
